export const teamsData = [
  {
    name: "Group 1",
    image: "/assets/userAvater1.svg",
    isActive: true,
    lastMessage: "Last message 1",
    lastSeenTime: "10:00 AM",
  },
  {
    name: "Group 1",
    image: "/assets/userAvater2.svg",
    isActive: true,
    lastMessage: "Last message 2",
    lastSeenTime: "11:00 AM",
  },
  {
    name: "Group 3",
    image: "/assets/userAvater3.svg",
    isActive: true,
    lastMessage: "Last message 3",
    lastSeenTime: "12:00 AM",
  },
  {
    name: "Group 4",
    image: "/assets/userAvater4.svg",
    isActive: true,
    lastMessage: "Last message 4",
    lastSeenTime: "02:00 AM",
  },
  {
    name: "Group 5",
    image: "/assets/userAvater5.svg",
    isActive: true,
    lastMessage: "Last message 5",
    lastSeenTime: "05:00 AM",
  },
  {
    name: "Group 6",
    image: "/assets/userAvater6.svg",
    isActive: false,
    lastMessage: "Last message 6",
    lastSeenTime: "06:00 AM",
  },
  {
    name: "Group 7",
    image: "/assets/userAvater7.svg",
    isActive: true,
    lastMessage: "Last message 7",
    lastSeenTime: "07:00 AM",
  },
  {
    name: "Group 8",
    image: "/assets/userAvater8.svg",
    isActive: true,
    lastMessage: "Last message 8",
    lastSeenTime: "08:00 AM",
  },
  {
    name: "Group 9",
    image: "/assets/userAvater9.svg",
    isActive: false,
    lastMessage: "Last message 9",
    lastSeenTime: "09:00 AM",
  },
  {
    name: "Group 10",
    image: "/assets/userAvater10.svg",
    isActive: false,
    lastMessage: "Last message 10",
    lastSeenTime: "12:00 AM",
  },
];

export const personalData = [
  {
    name: "Urmi",
    image: "/assets/userAvater1.svg",
    isActive: true,
    lastMessage: "Last message 1",
    lastSeenTime: "10:00 AM",
  },
  {
    name: "Samia",
    image: "/assets/userAvater2.svg",
    isActive: true,
    lastMessage: "Last message 2",
    lastSeenTime: "11:00 AM",
  },
  {
    name: "Lamia",
    image: "/assets/userAvater3.svg",
    isActive: true,
    lastMessage: "Last message 3",
    lastSeenTime: "12:00 AM",
  },
  {
    name: "Mim",
    image: "/assets/userAvater4.svg",
    isActive: true,
    lastMessage: "Last message 4",
    lastSeenTime: "02:00 AM",
  },
  {
    name: "Numan",
    image: "/assets/userAvater5.svg",
    isActive: true,
    lastMessage: "Last message 5",
    lastSeenTime: "05:00 AM",
  },
  {
    name: "Taslima",
    image: "/assets/userAvater6.svg",
    isActive: false,
    lastMessage: "Last message 6",
    lastSeenTime: "06:00 AM",
  },
  {
    name: "Oyshe",
    image: "/assets/userAvater7.svg",
    isActive: true,
    lastMessage: "Last message 7",
    lastSeenTime: "07:00 AM",
  },
  {
    name: "Lipi",
    image: "/assets/userAvater8.svg",
    isActive: true,
    lastMessage: "Last message 8",
    lastSeenTime: "08:00 AM",
  },
  {
    name: "Rafi",
    image: "/assets/userAvater9.svg",
    isActive: false,
    lastMessage: "Last message 9",
    lastSeenTime: "09:00 AM",
  },
  {
    name: "Rasel",
    image: "/assets/userAvater10.svg",
    isActive: false,
    lastMessage: "Last message 10",
    lastSeenTime: "12:00 AM",
  },
];
